pr: none
trigger:
  branches:
    include:
      - dev
  paths:
    include:
      - .azure-pipelines/mlops_create_environment.yml
      - deployment/mlworkspace_deployment.json
      - deployment/azuresearch_deployment.json
      - deployment/azfunction_deployment.json

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: mlops-vg


steps:
- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: '$(AZURE_RM_CONNECTION)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(RESOURCE_GROUP)'
    location: $(LOCATION)
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/deployment/mlworkspace_deployment.json'
    overrideParameters: '-baseName $(BASE_NAME) -location $(LOCATION) -workspace $(WORKSPACE_NAME) -resourceGroup $(RESOURCE_GROUP) -dataAccountName $(STORAGE_NAME) -storageContainer $(STORAGE_CONTAINER)'
    deploymentMode: 'Incremental'
  displayName: 'Deploy MLOps resources to Azure'

- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: '$(AZURE_RM_CONNECTION)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(RESOURCE_GROUP)'
    location: $(LOCATION)
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/deployment/azuresearch_deployment.json'
    overrideParameters: '-name $(AZURE_SEARCH_NAME)'
    deploymentMode: 'Incremental'
  displayName: 'Deploy Azure Search resources to Azure'

- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: '$(AZURE_RM_CONNECTION)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(RESOURCE_GROUP)'
    location: $(LOCATION)
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/deployment/azfunction_deployment.json'
    overrideParameters: '-appName $(AZURE_FUNCTION_NAME)'
    deploymentMode: 'Incremental'
  displayName: 'Deploy Azure Function resources to Azure'
