pr:
  branches:
    include:
    - dev
  paths:
    include:
    - mlops/clustering_pipeline/*
    - mlops/common/*
trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: mlops-vg

steps:
- template: mlops_base_pipeline.yml
  parameters:
    pipelinePublishScript: python3 -m mlops.clustering_pipeline.create_clustering_pipeline

- bash: |
    pip install --target="./find_similarity/.python_packages/lib/site-packages" -r ./find_similarity/requirements.txt
- task: CopyFiles@2
  displayName: "Copying ml folder"
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/ml'
    TargetFolder: "$(System.DefaultWorkingDirectory)/find_similarity/score_similarity/ml"
- task: CopyFiles@2
  displayName: "Copying models folder"
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/models'
    TargetFolder: "$(System.DefaultWorkingDirectory)/find_similarity/score_similarity/models"
- task: ArchiveFiles@2
  displayName: "Archive files"
  inputs:
    rootFolderOrFile: "$(System.DefaultWorkingDirectory)/find_similarity"
    includeRootFolder: false
    archiveFile: "$(System.DefaultWorkingDirectory)/find_similarity/build$(Build.BuildId).zip"
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/find_similarity/build$(Build.BuildId).zip'
    artifactName: 'drop'
