parameters:
  - name: pipelineid
    type: string

steps:
  - task: CmdLine@2
    name: 'getpipelineinfo'
    displayName: 'Get Pipeline Info'
    inputs:
      workingDirectory: $(Build.SourcesDirectory)
      script: |
        python -m mlops.get_pipeline_info --output_pipeline_file "pipeline_info.txt"
        readarray arr <"pipeline_info.txt"
        AML_PIPELINE_ID=${arr[0]}
        EXPERIMENTNAME=${arr[1]}
        echo "##vso[task.setvariable variable=${{ parameters.pipelineid }};isOutput=true]$AML_PIPELINE_ID"
        echo "##vso[task.setvariable variable=EXPERIMENTNAME;isOutput=true]$EXPERIMENTNAME"
    env:
      SP_APP_ID: '$(SP_APP_ID)'
      SP_APP_SECRET: '$(SP_APP_SECRET)'
      SUBSCRIPTION_ID: '$(SUBSCRIPTION_ID)'
      TENANT_ID: '$(TENANT_ID)'
