# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.134.1/containers/python-3/.devcontainer/base.Dockerfile
# Let's keep python on 3.8
ARG VARIANT="3.8"
FROM mcr.microsoft.com/vscode/devcontainers/python:0-${VARIANT}
ARG PYTHON="python3.8"

# [Optional] If your pip requirements rarely change, uncomment this section to add them to the image.
COPY requirements.txt /tmp/pip-tmp/
RUN pip3 --disable-pip-version-check --no-cache-dir install -r /tmp/pip-tmp/requirements.txt \
&& rm -rf /tmp/pip-tmp

# We need to enable access to exec into the container from azure webapps for linux
# See https://docs.microsoft.com/en-gb/azure/app-service/configure-custom-container?pivots=container-linux#enable-ssh
RUN apt-get update && \
DEBIAN_FRONTEND=noninteractive \
apt-get -y install default-jre-headless && \
apt-get -y install openssh-server && \
echo "root:Docker!" | chpasswd && \
apt-get clean && \
rm -rf /var/lib/apt/lists/*

COPY sshd_config /etc/ssh/

RUN python -m spacy download en_core_web_sm

RUN mkdir -p /usr/src/api
RUN mkdir -p /usr/src/api/powerskill
RUN mkdir -p /usr/src/api/models

WORKDIR /usr/src/api

COPY ./models /usr/src/api/models/
COPY ./powerskill/ /usr/src/api/powerskill/
COPY app.py /usr/src/api/

# https://docs.microsoft.com/en-gb/azure/app-service/configure-custom-container?pivots=container-linux#enable-ssh
EXPOSE 80 2222
EXPOSE 5000

ADD startup.sh /
RUN chmod +x /startup.sh

CMD ["/startup.sh"]
