POST {{$dotenv API_URL}}/process
Content-Type: application/json

{
    "values": [
        {
            "data": {
                "blobUrl": "https://youraccount.blob.core.windows.net/docs/different-roles-in-azure-portal.doc"
            },
            "recordId": "0"
        }
    ]
}