POST http://localhost:5000/process
Content-Type: application/json

{
    "values": [
        {
            "data": {
                "blobUrl": "https://youraccount.blob.core.windows.net/docs/Transforming-Content-with-GPT4o.pptx"
            },
            "recordId": "0"
        }
    ]
}