@baseUrl=http://0.0.0.0:5000
@apiKey={{$dotenv KEY}}

GET {{baseUrl}}/api/healthcheck
###

POST {{baseUrl}}/api/extraction
Ocp-Apim-Subscription-Key: {{apiKey}}
Content-Type: application/json

< rest_data.json