help: ## show this help
	@grep -E '^[a-zA-Z0-9_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
	| awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%s\033[0m|%s\n", $$1, $$2}' \
	| column -t -s '|'

deploy-base: ## deploy base services
	./scripts/deploy-base.sh

build-skill: ## build docker image for custom skill
	docker build -t clusterextractor .

	